### ISSUE TITLE
`ModuleNotFoundError: No module named 'smallworld'` when running from source

### ISSUE THREAD

**Issue by devos50** [sacs-epfl/decentralizepy#2]
When running the framework from source and following the instructions in the `README.md` file, I'm getting the following error:

```
mdevos@IC-ITs-MacBook-Pro-2 decentralizepy % python generate_graph.py --help
Traceback (most recent call last):
  File "/Users/mdevos/Documents/decentralizepy/generate_graph.py", line 1, in <module>
    from decentralizepy.graphs.Regular import Regular
  File "/Users/mdevos/Documents/decentralizepy/src/decentralizepy/graphs/__init__.py", line 2, in <module>
    from .SmallWorld import SmallWorld
  File "/Users/mdevos/Documents/decentralizepy/src/decentralizepy/graphs/SmallWorld.py", line 1, in <module>
    import smallworld
ModuleNotFoundError: No module named 'smallworld'
```

It seems like `smallworld` should be added to `requirements.txt`.

**Comment by devos50** [comment]
It looks like this requirement will be installed when running `setup.py`. Still, I think it's a good idea to fill `requirements.txt` with the required dependencies.
